from __future__ import annotations

from cad2d_ir.codecs.dxf import dxf_to_ir


def test_dxf_to_ir_parses_mvp_entities() -> None:
    dxf_text = "\n".join(
        [
            "0",
            "SECTION",
            "2",
            "HEADER",
            "9",
            "$INSUNITS",
            "70",
            "4",
            "0",
            "ENDSEC",
            "0",
            "SECTION",
            "2",
            "ENTITIES",
            "0",
            "LINE",
            "5",
            "A1",
            "8",
            "L-A",
            "10",
            "0",
            "20",
            "0",
            "11",
            "10",
            "21",
            "0",
            "0",
            "CIRCLE",
            "10",
            "5",
            "20",
            "5",
            "40",
            "2",
            "0",
            "ARC",
            "10",
            "1",
            "20",
            "1",
            "40",
            "3",
            "50",
            "0",
            "51",
            "90",
            "0",
            "LWPOLYLINE",
            "90",
            "3",
            "70",
            "1",
            "10",
            "0",
            "20",
            "0",
            "10",
            "1",
            "20",
            "0",
            "42",
            "0.25",
            "10",
            "1",
            "20",
            "1",
            "0",
            "TEXT",
            "10",
            "2",
            "20",
            "3",
            "40",
            "1.5",
            "1",
            "HELLO",
            "50",
            "30",
            "72",
            "1",
            "73",
            "2",
            "0",
            "ENDSEC",
            "0",
            "EOF",
            "",
        ]
    )

    ir = dxf_to_ir(dxf_text, validate=True)
    kinds = [entity["kind"] for entity in ir["entities"]]

    assert ir["header"]["units"] == "mm"
    assert kinds == ["LINE", "CIRCLE", "ARC", "LWPOLYLINE", "TEXT"]

    text = ir["entities"][-1]
    assert text["halign"] == "center"
    assert text["valign"] == "middle"
