from cad2d_ir.api import (
    DxfToIrResult,
    IrToDxfResult,
    convert_dgn_file_to_ir,
    convert_dwg_file_to_ir,
    convert_dwf_file_to_ir,
    convert_dxf_file_to_ir,
    convert_dxf_text_to_ir,
    convert_file_to_ir,
    convert_ir_file_to_dxf,
    convert_ir_to_dxf_text,
    convert_jww_file_to_ir,
    convert_mi_file_to_ir,
    convert_sxf_file_to_ir,
    dump_ir_json,
    load_ir_json,
)
from cad2d_ir.codecs.dxf import (
    SUPPORTED_DXF_TARGET_VERSIONS,
    dxf_to_ir,
    ir_to_dxf,
    read_dxf_file,
    resolve_dxf_output_encoding,
    write_dxf_file,
)
from cad2d_ir.constants import CURRENT_IR_VERSION
from cad2d_ir.diagnostics import (
    ALL_CODES,
    DIAGNOSTIC_CODES,
    ExportDiagnostic,
    diagnostic_code_details,
)
from cad2d_ir.importers import (
    ImportDiagnostic,
    ImportOptions,
    ImportResult,
    ImporterError,
    MissingOptionalDependencyError,
    UnsupportedSourceFormatError,
    detect_source_format,
)
from cad2d_ir.schema import IRValidationError, load_schema, validate_ir

__version__ = "0.9.3"

__all__ = [
    "__version__",
    "DxfToIrResult",
    "ALL_CODES",
    "DIAGNOSTIC_CODES",
    "CURRENT_IR_VERSION",
    "IRValidationError",
    "ExportDiagnostic",
    "ImportDiagnostic",
    "ImporterError",
    "ImportOptions",
    "ImportResult",
    "IrToDxfResult",
    "MissingOptionalDependencyError",
    "UnsupportedSourceFormatError",
    "SUPPORTED_DXF_TARGET_VERSIONS",
    "convert_dgn_file_to_ir",
    "convert_dwg_file_to_ir",
    "convert_dwf_file_to_ir",
    "convert_dxf_file_to_ir",
    "convert_dxf_text_to_ir",
    "convert_file_to_ir",
    "convert_ir_file_to_dxf",
    "convert_ir_to_dxf_text",
    "convert_jww_file_to_ir",
    "convert_mi_file_to_ir",
    "convert_sxf_file_to_ir",
    "dxf_to_ir",
    "dump_ir_json",
    "detect_source_format",
    "diagnostic_code_details",
    "ir_to_dxf",
    "load_ir_json",
    "load_schema",
    "read_dxf_file",
    "resolve_dxf_output_encoding",
    "validate_ir",
    "write_dxf_file",
]
